version: "3.10"

services:
  # Caddy reverse proxy - web-facing SSL server
  caddy:
    depends_on:
      - django
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    env_file:
      - envs/.env # env file - NOT committed to Git
    volumes:
      - caddy-data:/data/
      - caddy-data:/config/
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./staticdocs:/srv/staticdocs


  # Django web application
  django: &django
    build: .
    image: e12-django:built # build image and save for use by other containers
    depends_on:
      - postgis
    command: s/start-dev
    restart: always
    env_file:
      - envs/.env # env file - NOT committed to Git
    volumes:
      - .:/app/

  # PostgreSQL with PostGIS extension
  postgis:
    image: postgis/postgis:15-3.3
    volumes:
      - postgis-data:/var/lib/postgresql/data
    restart: always

  mkdocs:
    image: e12-django:built
    ports:
      - 8001:8001
    command: >
      sh -c "mkdocs build --config-file documentation/mkdocs.yml &&
        mkdocs serve --config-file documentation/mkdocs.yml"
    restart: always
    volumes:
      - .:/app/

volumes:
  caddy-data:
  postgis-data:

