# Generated by Django 5.1.2 on 2024-12-11 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0042_set_input_achieved_true"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S01JobPlannedHoursPerWeekLeadershipQIActivities",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=7,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalauditsubmission",
            name="S01LeadershipHours",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=7,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01JobPlannedHoursPerWeekLeadershipQIActivities",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=7,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="organisationalauditsubmission",
            name="S01LeadershipHours",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=7,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
