# Generated by Django 5.1 on 2024-10-31 22:03

from django.db import migrations


def update_assessment_records(apps, schema_editor):
    Assessment = apps.get_model("epilepsy12", "Assessment")
    Assessment.objects.filter(consultant_paediatrician_input_date__isnull=False).update(
        consultant_paediatrician_input_achieved=True
    )
    Assessment.objects.filter(
        epilepsy_specialist_nurse_input_date__isnull=False
    ).update(epilepsy_specialist_nurse_input_achieved=True)
    Assessment.objects.filter(paediatric_neurologist_input_date__isnull=False).update(
        paediatric_neurologist_input_achieved=True
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "epilepsy12",
            "0041_assessment_consultant_paediatrician_input_achieved_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(update_assessment_records),
    ]
