# Generated by Django 5.1.2 on 2024-11-23 13:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0042_set_input_achieved_true"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jersey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gid_0", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=10)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
            options={
                "verbose_name": "Jersey",
                "verbose_name_plural": "Jersey",
                "ordering": ("country",),
                "indexes": [
                    models.Index(fields=["gid_0"], name="epilepsy12__gid_0_7eae82_idx")
                ],
            },
        ),
    ]
