# Generated by Django 5.1.2 on 2024-11-23 13:16

# python imports
import os

# django imports
from django.db import migrations

# from django.apps import apps as django_apps
from django.apps import apps as django_apps
from django.contrib.gis.utils import LayerMapping

Jersey = django_apps.get_model("epilepsy12", "Jersey")

# Auto-generated `LayerMapping` dictionary for JerseyBoundary model
jerseyboundary_mapping = {
    "gid_0": "GID_0",
    "country": "COUNTRY",
    "geom": "MULTIPOLYGON",
}

# Get the path to the shape file
app_config = django_apps.get_app_config("epilepsy12")
app_path = app_config.path
jersey_shp_file_path = os.path.join(
    app_path, "shape_files", "gadm41_JEY_shp", "gadm41_JEY_0.shp"
)


def load_jersey_shape_file_mapping(apps, schema_editor):
    """
    Load the Jersey shape file mapping into the database
    """

    # Load the Jersey shape file mapping into the database
    lm = LayerMapping(
        Jersey,
        jersey_shp_file_path,
        jerseyboundary_mapping,
        transform=False,
        encoding="utf-8",
    )

    lm.save(strict=True, verbose=True)


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0043_jersey"),
    ]

    operations = [
        migrations.RunPython(load_jersey_shape_file_mapping),
    ]
