# Generated by Django 5.1.4 on 2025-01-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0044_alter_comorbidity_comorbidityentity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kpi",
            name="assessment_of_mental_health_issues",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "6. Assessment of Mental Health Issues",
                    "reference": "Percentage of children and young people with epilepsy where there is documented evidence that they have been asked about mental health either through clinical screening, or a questionnaire/measure.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="comprehensive_care_planning_agreement",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9A. Care Planning Agreement",
                    "reference": "Percentage of children and young people with epilepsy after 12 months where there is evidence of a comprehensive care plan that is agreed between the person, their family and/or carers and primary and secondary care providers, and the care plan has been updated where necessary.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="comprehensive_care_planning_content",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "9B. Care Planning Components",
                    "reference": "Percentage of children diagnosed with epilepsy with documented evidence of communication regarding core elements of care planning (items a - f).",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="epilepsy_specialist_nurse",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "2. Access to Epilepsy Specialist Nurse",
                    "reference": "Percentage of children and young people with epilepsy, with input by epilepsy specialist nurse within the first year of care.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="epilepsy_surgery_referral",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "3b. Epilepsy Surgery Referral",
                    "reference": "Percentage of ongoing children and young people meeting defined epilepsy surgery referral criteria with evidence of epilepsy surgery referral.",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="mental_health_support",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "7. Mental Health Support",
                    "reference": "Percentage of children and young people with epilepsy and a mental health problem who have evidence of mental health support",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="mri",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "5. MRI within 6 weeks",
                    "reference": "Percentage of children and young people with defined indications for an MRI, who had timely MRI within 6 weeks of request",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="paediatrician_with_expertise_in_epilepsies",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "1. Paediatrician with expertise in Epilepsy within 2 weeks",
                    "reference": "Percentage of children and young people with epilepsy, with input by a 'consultant paediatrician with expertise in epilepsies' within 2 weeks of initial referral",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="sodium_valproate",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "8. Medication and Reproduction Risks",
                    "reference": "Percentage of all females 12 years and above currently on valproate treatment with annual risk acknowledgement form completed",
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="tertiary_input",
            field=models.IntegerField(
                default=None,
                help_text={
                    "label": "3a. Tertiary Input",
                    "reference": "Percentage of children and young people meeting defined criteria for paediatric neurology referral, with input of tertiary care and/or CESS referral within the first year of care.",
                },
                null=True,
            ),
        ),
    ]
