# Generated by Django 5.1.2 on 2024-12-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("epilepsy12", "0049_case_unique_reference_number_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="case",
            unique_together={("nhs_number", "unique_reference_number")},
        ),
    ]
